backend:
  name: git-gateway
  branch: draft

media_folder: "images"
public_folder: "/images"

collections:
  - name: "artworks"
    label: "Artworks"

    files:
      - name: "artworks"
        label: "Artwork Gallery"
        file: "content/artworks.json"

        fields:
          - label: "Artwork"
            name: "artworks"
            widget: "list"
            summary: "{{fields.image}}"
            collapsed: false

            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                choose_url: false
